version: '3'

volumes:
  postgres-yuzuru:
    driver: local

services:
  bot:
    build: .
  db:
    image: postgres
    ports:
    - 5500:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=yuzuru
    volumes:
    - postgres-yuzuru:/var/lib/postgresql/data
